pipeline:
  build:
    image: python:3-alpine
    commands:
      - sleep 15
      - ping -c 5 database
      - python -c "import this"

services:
  database:
    image: mysql
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
